In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os

BASE_DIR = "/content/drive/MyDrive/property_valuation"

folders = [
    "data",
    "images",
    "outputs",
    "notebooks",
    "scripts"
]

for f in folders:
    os.makedirs(os.path.join(BASE_DIR, f), exist_ok=True)

BASE_DIR

'/content/drive/MyDrive/property_valuation'

In [3]:
import pandas as pd

DATA_PATH = f"/content/drive/MyDrive/property_valuation/kc_house_data.csv"
df = pd.read_csv(DATA_PATH)

df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [ ]:
df[['price', 'bedrooms', 'bathrooms', 'sqft_living', 'lat', 'long']].head()

      price  bedrooms  bathrooms  sqft_living      lat     long
0  221900.0         3       1.00         1180  47.5112 -122.257
1  538000.0         3       2.25         2570  47.7210 -122.319
2  180000.0         2       1.00          770  47.7379 -122.233
3  604000.0         4       3.00         1960  47.5208 -122.393
4  510000.0         3       2.00         1680  47.6168 -122.045

In [ ]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42
)

In [ ]:
train_df.to_csv(f"{BASE_DIR}/data/train.csv", index=False)
test_df.to_csv(f"{BASE_DIR}/data/test.csv", index=False)